name: Lint, test, and scan Helm charts
on:
  pull_request:
    branches:
      - main
      - release/**
  workflow_dispatch:
jobs:
  lint-test-scan:
    uses: Cray-HPE/hms-build-chart-workflows/.github/workflows/charts_lint_test_scan.yaml@v2
    with:
      lint-charts: ${{ github.event_name == 'pull_request' }}
      test-charts: false
      ct-yaml: ct.yaml
      scan-image-snyk-args: "--severity-threshold=high"
      scan-chart-snyk-args: "--severity-threshold=high"
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      ARTIFACTORY_ALGOL60_READONLY_USERNAME: ${{ secrets.ARTIFACTORY_ALGOL60_READONLY_USERNAME }}
      ARTIFACTORY_ALGOL60_READONLY_TOKEN: ${{ secrets.ARTIFACTORY_ALGOL60_READONLY_TOKEN }}
